version: 1.0

jobs:
  build:
    docker:
      - image: cimg/android:2024.10

    steps:
      - checkout

      # Project Environment setup
      - run:
          name: Make project setup script executable
          command: chmod +x project_setup.sh
      - run:
          name: Setting Up Project Environment
          command: ./project_setup.sh

      # Run Gradle Build
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Android Gradle Build
          command: ./gradlew clean assemble bundle --stacktrace

      # Store Builds
      - store_artifacts:
          path: app/build/outputs/apk
      - store_artifacts:
          path: app/build/outputs/bundle
